# This is a basic workflow to help you get started with Actions

name: First WorkFlow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Select Environment'
        required: true
        default: 'dev'
        options:
          - dev
          - Dev
          - stage
          - prod
      restart_pingfederate:
        type: choice
        description: 'Restart PingFederate?'
        required: true
        default: 'no'
        options:
          - 'yes'
          - 'no'
      repo_tag:
        description: 'Enter Repo Tag (e.g., v1.2.0)'
        required: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: GHATest

    environment:
      name: ${{ github.event.inputs.environment }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - name: Display Input Parameters
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Repo Tag: ${{ github.event.inputs.repo_tag }}"
          echo "Restart PingFederate: ${{ github.event.inputs.restart_pingfederate }}"
      
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest
      - name: Display Terraform version
        run: terraform version
        
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      - name: Check and Install Ansible (if not installed)
        run: |
          if ! command -v ansible &> /dev/null
          then
              echo "⚠️ Ansible not found. Installing via pip..."
          else
              echo "✅ Ansible is already installed."
          fi